name: contacts_app
description: "A contacts management app with Supabase integration"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.10
  intl: ^0.19.0
  url_launcher: ^6.2.5
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env