name: business_card
description: Flutter Business Card
publish_to: 'none'
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_icons: ^1.1.0
  font_awesome_flutter: ^10.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  fonts:
  - family: Pacifico
    fonts:
      - asset: fonts/Pacifico-Regular.ttf
  - family: SourceSansPro
    fonts:
      - asset: fonts/SourceSansPro-Regular.ttf
  assets:
    - images/

